//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_intern.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class streetlampData
    {
        public Nullable<int> LAYER { get; set; }
        public string ID { get; set; }
        public string ORGAN { get; set; }
        public Nullable<int> OP_CODE { get; set; }
        public Nullable<System.DateTime> BURY_DATE { get; set; }
        public string NUM { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<int> USEMODE { get; set; }
        public Nullable<int> DATAMODE { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> POINT_X { get; set; }
        public Nullable<decimal> POINT_Y { get; set; }
        public string TOWNSHIP { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public Nullable<int> STATE { get; set; }
        public string DATA1 { get; set; }
        public string DATA2 { get; set; }
        public string LEVEL { get; set; }
    }
}
